apiVersion: v1
kind: Service
metadata:
  name: zalenium
  namespace: zalenium
spec:
  type: LoadBalancer
  loadBalancerIP: "35.197.32.233"
  sessionAffinity: None
  ports:
    - name: zalenium
      protocol: TCP
      port: 4444
      targetPort: 4444
  selector:
    zalenium: hub
